services:

    #The name of the service is referenced in the code. Caution if changed
    riper.common.exception_transformer.resolver:
        class: Riper\Bundle\ExceptionTransformerBundle\Resolver\ExceptionMappingResolver

    #The name of the service is referenced in the code. Caution if changed
    riper.common.exception_transformer.transformers.http_exception_transformer:
        class: Riper\Bundle\ExceptionTransformerBundle\ExceptionTransformer\HttpExceptionTransformer
        arguments : [ %riper_exception_mapping.shortcuts% ]
        calls :
            - [ "addMap" , [ %riper_exception_mapping.exception_map% ] ]
        tags:
            - { name: riper.exception.transformer, namespace_scope: "" }


    riper.common.exception_transformer.http_exception_listener:
        class: Riper\Bundle\ExceptionTransformerBundle\Listener\ExceptionTransformerListener
        arguments: [ @riper.common.exception_transformer.resolver ]
        tags:
            - { name : kernel.event_subscriber }

#    riper.common.error_handler.exception_to_http_exception_listener:
#            class: Riper\Bundle\ErrorRendererBundle\Listener\ExceptionToHttpExceptionListener
#            arguments : [ %riper_exception_mapping% ]
#            tags:
#                - { name : kernel.event_subscriber }
